Repository jenkinsci/autograding-plugin, pull requests merged in 2020-04, with the labels that each got.

#10 Add `@NonNull` default annotation
  README.md
  src/main/java/io/jenkins/plugins/grading/package-info.java
Labels: internal

#11 Add configuration screen for freestyle jobs (and snippet generator)
  src/main/java/io/jenkins/plugins/grading/AutoGrader.java
  src/main/resources/io/jenkins/plugins/grading/AutoGrader/config.jelly
  src/main/resources/io/jenkins/plugins/grading/AutoGrader/config.properties
  src/main/resources/io/jenkins/plugins/grading/config.jelly
Labels: enhancement

#2 Add missing tests for `CoverageScore`
  src/test/java/io/jenkins/plugins/grading/CoverageScoreTests.java
Labels: test

#12 Cleanup of analysis warnings
  etc/assertj-templates/assertions_entry_point_class_template.txt
  src/main/java/io/jenkins/plugins/grading/AnalysisConfiguration.java
  src/main/java/io/jenkins/plugins/grading/AnalysisScore.java
  src/main/java/io/jenkins/plugins/grading/AutoGrader.java
  src/main/java/io/jenkins/plugins/grading/Configuration.java
  src/main/java/io/jenkins/plugins/grading/CoverageConfiguration.java
  src/main/java/io/jenkins/plugins/grading/CoverageScore.java
  src/main/java/io/jenkins/plugins/grading/PitConfiguration.java
  src/main/java/io/jenkins/plugins/grading/PitScore.java
  src/main/java/io/jenkins/plugins/grading/TestConfiguration.java
  src/main/java/io/jenkins/plugins/grading/TestScore.java
  src/test/java/io/jenkins/plugins/grading/AnalysisScoreTest.java
  src/test/java/io/jenkins/plugins/grading/TestScoreTest.java
Labels: internal

#14 Improve user interface
  src/main/java/io/jenkins/plugins/grading/Score.java
  src/main/resources/io/jenkins/plugins/grading/AutoGradingViewModel/index.jelly
  src/main/resources/io/jenkins/plugins/grading/AutoGradingViewModel/index.properties
  src/main/webapp/css/custom-style.css
  src/test/java/io/jenkins/plugins/grading/CoverageScoreTests.java
  src/test/java/io/jenkins/plugins/grading/ScoreTest.java
Labels: enhancement

#15 Add branch coverage
  src/main/java/io/jenkins/plugins/grading/AutoGrader.java
  src/main/java/io/jenkins/plugins/grading/CoverageScore.java
  src/main/java/io/jenkins/plugins/grading/Score.java
  src/main/resources/io/jenkins/plugins/grading/AutoGradingViewModel/index.jelly
  src/main/webapp/css/custom-style.css
  src/test/java/io/jenkins/plugins/grading/CoverageScoreTests.java
  src/test/java/io/jenkins/plugins/grading/ScoreTest.java
Labels: enhancement

#18 Add Test for PitConfiguration in PitScoreTest
  src/test/java/io/jenkins/plugins/grading/PitScoreTest.java
Labels: test

#22 Add serialization test
  pom.xml
  src/main/java/io/jenkins/plugins/grading/AggregatedScore.java
  src/main/java/io/jenkins/plugins/grading/AggregatedScoreXmlStream.java
  src/main/java/io/jenkins/plugins/grading/AnalysisConfiguration.java
  src/main/java/io/jenkins/plugins/grading/AnalysisScore.java
  src/main/java/io/jenkins/plugins/grading/AutoGradingBuildAction.java
  src/main/java/io/jenkins/plugins/grading/AutoGradingJobAction.java
  src/main/java/io/jenkins/plugins/grading/Configuration.java
  src/main/java/io/jenkins/plugins/grading/CoverageConfiguration.java
  src/main/java/io/jenkins/plugins/grading/CoverageScore.java
  src/main/java/io/jenkins/plugins/grading/PitConfiguration.java
  src/main/java/io/jenkins/plugins/grading/PitScore.java
  src/main/java/io/jenkins/plugins/grading/Score.java
  src/main/java/io/jenkins/plugins/grading/TestConfiguration.java
  src/main/java/io/jenkins/plugins/grading/TestScore.java
  src/test/java/io/jenkins/plugins/grading/AggregatedScoreXmlStreamTest.java
  src/test/resources/io/jenkins/plugins/grading/auto-grading.xml
Labels: tests

#28 Add JSON schema and configuration help
  etc/configuration.json
  pom.xml
  src/main/resources/io/jenkins/plugins/grading/AutoGrader/config.jelly
  src/main/resources/io/jenkins/plugins/grading/AutoGrader/config.properties
  src/main/resources/io/jenkins/plugins/grading/AutoGrader/help-configuration.html
Labels: documentation
